# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef32797a7843aa38cc11b80ec7793a21ce7cdbf32e631f56c654caccc58e14837a26ef50faf0f085e1a7672503f8bfed05876a54c307e2d6eb31b008b16d2056

test:
  secret_key_base: c3492807fd0bfd8bc3e2984d99ae51382ade175e9433cceb7764aab6e863e6f9c3e40a4e89b5731642a5f571da7d64411881fcd0db4f1bd39a84b2e34c541809

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
